import {
  loginUser,
  logout,
  registerHcp,
  updateHcpProfile,
} from "./AuthService";
import {
  createPatientAccount,
  fetchPatientList,
  filterPatientList,
  updatePatientProfile,
  updateMedicalCondition,
  updateAllergy,
  updateStrokeRisk,
  updateBleedingRisk,
  updateWarfarinQuality,
  updateHealthGoal,
  updateMedication,
  updateBloodThinner,
  updateInrRecord,
  updateCreatinineRecord,
  deletePatientById,
  deleteAllSelectedPatients,
  setCurrentPatient,
} from "./PatientService";

export {
  loginUser,
  logout,
  registerHcp,
  updateHcpProfile,
  createPatientAccount,
  fetchPatientList,
  filterPatientList,
  updatePatientProfile,
  updateMedicalCondition,
  updateAllergy,
  updateStrokeRisk,
  updateBleedingRisk,
  updateWarfarinQuality,
  updateHealthGoal,
  updateMedication,
  updateBloodThinner,
  updateInrRecord,
  updateCreatinineRecord,
  deletePatientById,
  deleteAllSelectedPatients,
  setCurrentPatient,
};
