import { loginUser, logout, registerHcp } from "./AuthService";
import {
  createPatientAccount,
  fetchPatientList,
  filterPatientList,
  updatePatientProfile,
  updateMedicalCondition,
  updateAllergy,
  updateStrokeRisk,
  updateBleedingRisk,
  updateWarfarinQuality,
  updateHealthGoal,
  deletePatientById,
  deleteAllSelectedPatients,
  setCurrentPatient,
} from "./PatientService";

export {
  loginUser,
  logout,
  registerHcp,
  createPatientAccount,
  fetchPatientList,
  filterPatientList,
  updatePatientProfile,
  updateMedicalCondition,
  updateAllergy,
  updateStrokeRisk,
  updateBleedingRisk,
  updateWarfarinQuality,
  updateHealthGoal,
  deletePatientById,
  deleteAllSelectedPatients,
  setCurrentPatient,
};
